plugins {
    id 'net.fabricmc.fabric-loom'
    id 'maven-publish'
}

base {
    archivesName = 'skm-client-26.2'
}

version = '1.0.6'

loom {
    splitEnvironmentSourceSets()
    mods {
        'skm' {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft 'com.mojang:minecraft:26.2'
    implementation 'net.fabricmc:fabric-loader:0.19.5'
    implementation 'net.fabricmc.fabric-api:fabric-api:0.161.0+26.2'
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand(version: project.version)
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
}
